- type: job
  id: Virologist
  name: job-name-virologist
  description: job-description-virologist
  playTimeTracker: JobVirologist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 108000 # 30 hours
  startingGear: VirologistGear
  icon: "JobIconVirologist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Virology
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Medical
  wage: 70
  #end-backmen: currency

- type: startingGear
  id: VirologistGear
  equipment:
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    socks: ClothingUnderwearSocksDoctor
    id: VirologistPDA

- type: chameleonOutfit
  id: VirologistChameleonOutfit
  job: Virologist
  equipment:
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    socks: ClothingUnderwearSocksDoctor
