- type: department
  id: Taipan
  name: department-Taipan
  description: department-Taipan-description
  color: "#D381C9"
  roles:
  - TaipanAtmosphericsEngineer
  - TaipanBotanist
  - TaipanCargotech
  - TaipanChef
  - TaipanCommunicationsOfficer
  - TaipanMedic
  - TaipanParamedic
  - TaipanRecruit
  - TaipanResearchDirector
  - TaipanResearcher
  - TaipanTechnician
  - TaipanTechnicalOperationsSupervisor
  editorHidden: true

- type: department
  id: SpecialOperationsCorps
  name: department-SpecialOperationsCorps
  description: department-SpecialOperationsCorps-description
  color: "#7fffd4"
  roles:
  - CentralCommandSpecialOperationsOfficer
  - CBURNLeader
  - CBURNAgent
  - ERTLeaderAmber
  - ERTLeaderRed
  - ERTLeaderGamma
  - ERTSecurityAmber
  - ERTSecurityRed
  - ERTSecurityGamma
  - ERTMedicalAmber
  - ERTMedicalRed
  - ERTMedicalGamma
  - ERTEngineerAmber
  - ERTEngineerRed
  - ERTEngineerGamma
  - ERTJanitorAmber
  - ERTJanitorRed
  - ERTJanitorGamma
  editorHidden: true
  weight: 120
