- type: antag
  id: HeadRev
  name: roles-antag-rev-head-name
  antagonist: true
  setPreference: true
  objective: roles-antag-rev-head-objective
  guides: [ Revolutionaries ]
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 100h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 20h

- type: antag
  id: Rev
  name: roles-antag-rev-name
  antagonist: true
  setPreference: false
  objective: roles-antag-rev-objective
  guides: [ Revolutionaries ]

- type: startingGear
  id: HeadRevGear
  storage:
    back:
    - Flash
    - ClothingEyesGlassesSunglasses
    - EncryptionKeySyndie
